### ISSUE TITLE
parso 0.8.0 dropped python2 support

### ISSUE THREAD

**Issue by nritsche** [jrs65/py3port#2]
https://pypi.org/project/parso/

```
$ py3port
########## ./versioneer.py ###########
Preprocessing:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/parso/grammar.py", line 252, in load_grammar
    return _loaded_grammars[path]
KeyError: '/usr/local/lib/python3.8/dist-packages/parso/python/grammar27.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/parso/grammar.py", line 255, in load_grammar
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/parso/python/grammar27.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/py3port", line 8, in <module>
    sys.exit(main())
  File "/home/rick/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/rick/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/rick/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rick/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/py3port/main.py", line 391, in main
    process(filename)
  File "/usr/local/lib/python3.8/dist-packages/py3port/main.py", line 358, in process
    preprocess(filename)
  File "/usr/local/lib/python3.8/dist-packages/py3port/main.py", line 304, in preprocess
    tree = parso.parse(fh.read(), version='2.7')
  File "/usr/local/lib/python3.8/dist-packages/parso/__init__.py", line 57, in parse
    grammar = load_grammar(version=version)
  File "/usr/local/lib/python3.8/dist-packages/parso/grammar.py", line 264, in load_grammar
    raise NotImplementedError(message)
NotImplementedError: Python version 2.7 is currently not supported.
```

**Comment by jrs65** [comment]
Hmmm.... out of interest why do you need to use `py3port`?
